### ISSUE TITLE
Friendly peer names

### ISSUE THREAD

**Issue by 0xERR0R** [mdlayher/wireguard_exporter#10]
I use linuxserver/wireguard docker image as wireguard server and I would like to use your prometheus exporter. To specify a friendly name I can map client's key to the name. Would it be possible to use the peer number for this mapping? For example "Peer1=name1"? It would be handy to define the names in this way, there is no need to use the client key. What do you think about this feature?

**Comment by mdlayher** [comment]
There is no concept of peer number in the low level APIs. I recently added support for a TOML mapping file so I recommend giving that a try. The public key of a peer is the only way to guarantee uniqueness.

I think there's nothing to do here so I'm going to close this issue, but feel free to ping if you feel otherwise. Thanks!
